name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip openjdk-17-jdk \
            unzip git build-essential libffi-dev libssl-dev zlib1g-dev \
            libncurses5-dev libsqlite3-dev libreadline-dev libbz2-dev liblzma-dev
          pip install --user buildozer cython

      - name: Build APK
        run: |
          export PATH=$PATH:$HOME/.local/bin
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: gf07-apk
          path: bin/*.apk
