name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            build-essential \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            zlib1g-dev \
            libjpeg-dev \
            libfreetype6-dev \
            curl

      - name: Install Android SDK & NDK
        run: |
          mkdir -p $HOME/android-sdk
          cd $HOME/android-sdk
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools.zip -d cmdline-tools
          mkdir -p cmdline-tools/latest
          mv cmdline-tools/cmdline-tools/* cmdline-tools/latest/
          yes | cmdline-tools/latest/bin/sdkmanager --licenses
          cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0" "ndk;23.1.7779620"
          echo "export ANDROIDSDK=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export ANDROIDNDK=$HOME/android-sdk/ndk/23.1.7779620" >> $GITHUB_ENV
          echo "export PATH=$HOME/android-sdk/platform-tools:$HOME/android-sdk/build-tools/31.0.0:$PATH" >> $GITHUB_ENV

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: gf07tracker-apk
          path: bin/*.apk
