name: Build APK

on:
  workflow_dispatch: # so you can manually trigger from Actions tab

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            build-essential \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            zlib1g-dev \
            libjpeg-dev \
            libfreetype6-dev

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: gf07tracker-apk
          path: bin/*.apk
